paths:
  results: results/
  plots: plots/
  data: data/
  sessions: sessions/
first date: 1988
last date: "December 1997"
segment: clrd
granularity: yearly
workflow:
  dataset: clrd
  clrd_lob: comauto
session:
  path: sessions/clrd.yml
